on: 
  push:
    branches:
      - dev
name: 🚀 Deploy to dev on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ftp.jeta2726.odns.fr
        username: adherents-dev@adherents-dev.jeta2726.odns.fr
        password: ${{ secrets.dev_ftp_password }}
