on:
    push:
      tags:
        - release.v**
name: 🚀 Deploy to main on tag push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4
      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ftp.jeta2726.odns.fr
          username: adherents-prod@adherents.association-kdance.fr
          password: ${{ secrets.prod_ftp_password }}
